/*let nome = "marcos" //string
let idade = 17 // int ou number
let altura = 1.50 // float ou number
let temgato = true //boolean
const p1 = 3.1415

console.log (" oi eu sou "+nome+" e eu tenho "+idade+" anos")

console.log('oi eu sou $(nome) e eu tenho $(idade) anos')

let pessoas ={
    nome:'marcos',
    idade:'18',
    sexo:'M',
    cpf:'432.234.334-44',
    altura:1.80
}

console.log(pessoas.nome)
*/

/*let n1 = 200
let n2 = 17.99
let resultado = n1 + n2
console.log(resultado)*/
